### PR TITLE
feat: scalable UI

### PR DESCRIPTION
**Pull request by Ark2000**
This pull request fixed all UI scaling issues.

**Now we can adjust global UI size like this below.** (Of course the plugin will detect DPI and choose a suitable scale automatically or you can do it manually in settings menu

- font size: 24

- font size: 16

- font size: 8

- font size: 32

**Also, we can customize font easily now.** I guess it will be pixel-game friendly.

Change font here:

### CODE REVIEW

**Comment by tarwich** [comment]
Tested with the `ui-fix` branch. Feature-wise works well. Something is a bit odd with the font size detection, but at least it's useable. 


https://github.com/Ark2000/PankuConsole/assets/334149/196ff5d6-d697-4a08-93eb-19f745c1014b

**Comment by Ark2000** [comment]
> Tested with the `ui-fix` branch. Feature-wise works well. Something is a bit odd with the font size detection, but at least it's useable.
> 
>  Screen.Recording.2024-05-07.at.08.02.49c.mp4

should work now.

**Comment by FabriceCastel** [comment]
Can confirm this seems to scale appropriately now! Also was able to configure the font so it wouldn't use the pixel art font I'm running with for my game. The only thing you missed I think is that the color of the font in the title bar still uses the default theme color for the project. Should be a matter of just adding that override to the panku theme, other than that it looks great!
 
image

**Comment by FabriceCastel** [comment]
I just added a font color override for the `Label` node type to address that last thing and it worked as intended FWIW

**Comment by FabriceCastel** [comment]
Also, I'm only seeing this now - but there's a typo in the title (`Interative -> Interactive`). Huge bug, I don't know if I'm going to be able to use the console with that there :OOOOOO

**Comment by Ark2000** [comment]
> Also, I'm only seeing this now - but there's a typo in the title (`Interative -> Interactive`). Huge bug, I don't know if I'm going to be able to use the console with that there :OOOOOO

Here's a humorous way to respond to that comment about the typo in the issue title:

Oops, my bad! That pesky "Interative" typo must have been a bug planted by my arch-nemesis, the dastardly Typo Villain! Fear not, for I shall vanquish this foe with my trusty backspace key and restore order to the console! 🗡️💻 Your faith in my coding prowess shall be rewarded once more! 🤺

**Comment by FabriceCastel** [comment]
> > Can confirm this seems to scale appropriately now! Also was able to configure the font so it wouldn't use the pixel art font I'm running with for my game. The only thing you missed I think is that the color of the font in the title bar still uses the default theme color for the project. Should be a matter of just adding that override to the panku theme, other than that it looks great!
> > image
> 
> I'm not sure what caused the issue, I tested it on several different devices, and the title bar text color was white as expected. It's good to know that you were able to fix it easily. I'll pay more attention if others raise similar issues in the future.

I've got a default theme set up on my project that overrides the font color attribute for `Label` nodes. The Panku theme doesn't define any behaviour for `Label` `font color` properties, so Godot falls back to the project-wide default theme and uses whatever color is configured there (in my case, that brown-ish color). I'm maybe 80% sure that's what's going on, I'm still relatively new to the theme system in Godot.

**Pull request merged**
